<a href="https://colab.research.google.com/github/Shankaracharya06/Control_Statements/blob/main/Copy_of_NumpyMethods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

In [14]:
print((np.__version__))         # 1.26.4 (verison of numpy)

# Priority of typcasting during converting into array   ------------->    bool < int < float < complex < str < set < dict

list1 = [1, 4, 5, 6]
print(np.array(list1))          # [1, 4, 5, 6]

list2 = [1, 4.0, 5, 6]
print(np.array(list2))          # [1., 4., 5., 6.]

list3 = [1, 4, "hello", 5, 6]
print(np.array(list3))          # ['1' '4' 'hello' '5' '6']

list4 = [1, 4,8, 5+4j, 6]
print(np.array(list4))          # [1.+0.j 4.+0.j 8.+0.j 5.+4.j 6.+0.j]

1.26.4
[1 4 5 6]
[1. 4. 5. 6.]
['1' '4' 'hello' '5' '6']
[1.+0.j 4.+0.j 8.+0.j 5.+4.j 6.+0.j]


In [15]:
arr1D = np.array([1,5,8,6,9])
print(arr1D)         # [1 5 8 6 9]
print(arr1D.ndim)
print(arr1D.dtype)
print(arr1D.shape)   # (5,)
print(arr1D.reshape)


arr2D = np.array([
                  [1,2,3],
                  [5,8,11]
                ])
print(arr2D)         # [1 5 8 6 9]
print(arr2D.ndim)
print(arr2D.dtype)
print(arr2D.shape)   # (5,)
print(arr2D.reshape)

arr3D = np.array([
                  [[1,2,7],[5,8,3]],
                  [[8,7,5],[6,3,7]]
                 ])
print(arr3D)         # [1 5 8 6 9]
print(arr3D.ndim)
print(arr3D.dtype)
print(arr3D.shape)   # (5,)
print(arr3D.reshape)

np.arange(0,1001,2)

[1 5 8 6 9]
1
int64
(5,)
<built-in method reshape of numpy.ndarray object at 0x7894818693b0>
[[ 1  2  3]
 [ 5  8 11]]
2
int64
(2, 3)
<built-in method reshape of numpy.ndarray object at 0x7894818699b0>
[[[1 2 7]
  [5 8 3]]

 [[8 7 5]
  [6 3 7]]]
3
int64
(2, 2, 3)
<built-in method reshape of numpy.ndarray object at 0x7894818682d0>


array([   0,    2,    4,    6,    8,   10,   12,   14,   16,   18,   20,
         22,   24,   26,   28,   30,   32,   34,   36,   38,   40,   42,
         44,   46,   48,   50,   52,   54,   56,   58,   60,   62,   64,
         66,   68,   70,   72,   74,   76,   78,   80,   82,   84,   86,
         88,   90,   92,   94,   96,   98,  100,  102,  104,  106,  108,
        110,  112,  114,  116,  118,  120,  122,  124,  126,  128,  130,
        132,  134,  136,  138,  140,  142,  144,  146,  148,  150,  152,
        154,  156,  158,  160,  162,  164,  166,  168,  170,  172,  174,
        176,  178,  180,  182,  184,  186,  188,  190,  192,  194,  196,
        198,  200,  202,  204,  206,  208,  210,  212,  214,  216,  218,
        220,  222,  224,  226,  228,  230,  232,  234,  236,  238,  240,
        242,  244,  246,  248,  250,  252,  254,  256,  258,  260,  262,
        264,  266,  268,  270,  272,  274,  276,  278,  280,  282,  284,
        286,  288,  290,  292,  294,  296,  298,  3

In [16]:
new_arr = np.linspace(-4,5,50)
# print(new_arr)              # [-4.         -3.81632653 -3.63265306 -3.44897959 -3.26530612 -3.08163265
                            # -2.89795918 -2.71428571 -2.53061224 -2.34693878 -2.16326531 -1.97959184
                            # -1.79591837 -1.6122449  -1.42857143 -1.24489796 -1.06122449 -0.87755102
                            # -0.69387755 -0.51020408 -0.32653061 -0.14285714  0.04081633  0.2244898
                            #  0.40816327  0.59183673  0.7755102   0.95918367  1.14285714  1.32653061
                            #  1.51020408  1.69387755  1.87755102  2.06122449  2.24489796  2.42857143
                            #  2.6122449   2.79591837  2.97959184  3.16326531  3.34693878  3.53061224
                            #  3.71428571  3.89795918  4.08163265  4.26530612  4.44897959  4.63265306
                            #  4.81632653  5.        ]
new_arr = np.random.randint(10.5,26.5,50)
# print(new_arr)              # [23 16 21 18 18 24 14 23 18 18 12 19 17 14 11 20 21 11 10 10 14 13 14 24
                            #  20 25 21 24 16 20 15 17 12 11 14 24 19 17 15 11 11 16 14 15 14 19 15 14
                            #  22 11]
new_arr = np.random.rand(5)
# print(new_arr)              # [0.79332798 0.56400245 0.33369816 0.57638247 0.88839336]

new_arr = np.random.randn(20)
# print(new_arr)              # [-0.85172822 -0.21545446 -0.78639605  1.63299493  1.73847166]

fruits = ['apple','orange','banana','pomogrenate']
new_arr = np.random.choice(fruits)
# print(new_arr)                # give any random item from the collection(fruits)

songs = ['perfect', 'blinding lights', 'night change']
np.random.shuffle(songs)
# print(songs)                  # it will shuffle the original collection(songs) i.e rearrange the oroginal collection


In [25]:
# print(np.zeros(5))              # [0. 0. 0. 0. 0.]

# print(np.zeros((2,5)))          # [[0. 0. 0. 0. 0.]
                                 #  [0. 0. 0. 0. 0.]]

# print(np.zeros((3,2,4)))        #[[[0. 0. 0. 0.]
                                # [0. 0. 0. 0.]]
                                #  [[0. 0. 0. 0.]
                                #  [0. 0. 0. 0.]]
                                #   [[0. 0. 0. 0.]
                                #   [0. 0. 0. 0.]]]

print(np.ones(5))               # [1. 1. 1. 1. 1.]

print(np.ones((2,5)))           # [[1. 1. 1. 1. 1.]
                                #  [1. 1. 1. 1. 1.]]

print(np.ones((3,4,6)))         # [[[1. 1. 1. 1. 1. 1.]
                                #   [1. 1. 1. 1. 1. 1.]
                                #   [1. 1. 1. 1. 1. 1.]
                                #   [1. 1. 1. 1. 1. 1.]]

                                # [[1. 1. 1. 1. 1. 1.]
                                #   [1. 1. 1. 1. 1. 1.]
                                #   [1. 1. 1. 1. 1. 1.]
                                #   [1. 1. 1. 1. 1. 1.]]

                                # [[1. 1. 1. 1. 1. 1.]
                                #   [1. 1. 1. 1. 1. 1.]
                                #   [1. 1. 1. 1. 1. 1.]
                                #   [1. 1. 1. 1. 1. 1.]]]

print(np.identity(5))           # [[1. 0. 0. 0. 0.]
                                #  [0. 1. 0. 0. 0.]
                                #  [0. 0. 1. 0. 0.]
                                #  [0. 0. 0. 1. 0.]
                                #  [0. 0. 0. 0. 1.]]



[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
